### ISSUE TITLE
Problem with options.outputDirLocalRepo

### ISSUE THREAD

**Issue by ToppScorer** [khalilou88/jnxplus#1438]
I have the following part in the nx.json:

```
    "backend-deploy": {
      "cache": true,
      "executor": "@jnxplus/nx-maven:run-task",
      "options": {
        "task": "deploy"
      },
      "dependsOn": [
        "^backend-install"
      ],
      "outputs": [
        "{options.outputDirLocalRepo}",
        "{projectRoot}/.flattened-pom.xml",
        "{projectRoot}/target"
      ]
    },
```

and in one sub-module this project.json overriding the default task:

```
    "backend-deploy": {
      "executor": "nx:run-commands",
      "options": {
        "cwd": "{projectRoot}",
        "envFile": "{projectRoot}/.env",
        "commands": [
          "echo Test",
          "docker login",
        ],
        "parallel": false
      },
      "inputs": ["default", "{projectRoot}/.env"]
    },
```

When running `npx nx affected --targets backend-deploy` now, I get the following message: 

```
service: > echo 'Test' --outputDirLocalRepo=[localRepo]
service: > docker login  --outputDirLocalRepo=[localRepo]
```

with the following error:

```
service: unknown flag: --outputDirLocalRepo
```

Is it expected, that the `outputDirLocalRepo` is appended to every command, even if overridden by a different executor?

When I remvove the `{options.outputDirLocalRepo}` from the `outputs` in the nx.json, it's working.

**Comment by khalilou88** [comment]
Hi @ToppScorer,

Your use case is not covered.
To make it work i will add two changes:

- Don't set outputDirLocalRepo if it's present in target.options
https://github.com/khalilou88/jnxplus/pull/1439

- Add option `skipSettingOutputDirLocalRepo`.
I think this is what you need but don't know is it will works

**Comment by khalilou88** [comment]
@ToppScorer I published version v1.16.0 with the first change. Can you try it ? you need to set outputDirLocalRepo in options object.

**Comment by ToppScorer** [comment]
@khalilou88 Unfortunately I'm not able to test it, because I run into some trouble when updating from version 1.8.0 to version 1.16.0. There seems to be a regression, the `skipProjectWithoutProjectJson` flag does not seem to work anymore. I'm getting `Error: Can't find project for file: [redacted]/pom.xml` for a project that does not have a `project.json`. This https://github.com/khalilou88/jnxplus/blob/892cbf32a11c6c648daf9ac17a902522fb31fba6/packages/nx-maven/src/graph/create-dependencies.ts#L42 check is done too early IMHO. Maybe there should be a new ticket for that.

**Comment by khalilou88** [comment]
@ToppScorer 

The error should come from this condition:

```
          const project = projects.find(
            (element) =>
              joinPathFragments(element.projectRoot, 'pom.xml') === filePath,
          );
```

Could you please add a `console log` to see the value of both values ?

**Comment by khalilou88** [comment]
I published version 1.16.1-next.0, with a better condition, maybe it will work for you?
https://github.com/khalilou88/jnxplus/pull/1442

**Comment by ToppScorer** [comment]
@khalilou88 This is the output:

```
filePath: [redacted: path the to POM without project.json]/pom.xml
normalizedFilePath: [redacted: path the to POM without project.json]/pom.xml
```

**Comment by ToppScorer** [comment]
@khalilou88 Ok, I will try to explain it:

1. The path for both variable is exactly the same
2. The project without the `project.json` is in a folder `[workspace-root]/apps/spring-boot/service/infrastructure`
3. The output for both is exactly `apps/spring-boot/service/infrastructure/pom.xml`
4. The nx.json contains
```
  "plugins": [
    {
      "plugin": "@jnxplus/nx-maven",
      "options": {
        "localRepoRelativePath": ".m2/repository",
        "mavenRootDirectory": "libs/spring-boot/root",
        "graphOptions": {
          "skipProjectWithoutProjectJson": true
        }
      }
    }
  ]
```
5. The `infrastructure` project is in a subfolder of another Maven project, but has no relation to it.

**Comment by khalilou88** [comment]
`mavenRootDirectory` was not designed to work like this. The idea was to put all spring project in a sub-folder.

We need a reproduction to update the calculation of project root : `[workspace-root] + mavenRootDirectory + apps/spring-boot/service/infrastructure`

**Comment by khalilou88** [comment]
I published version 1.17.0-next.0 to add your case.
PR here: https://github.com/khalilou88/jnxplus/pull/1444

**Comment by ToppScorer** [comment]
@khalilou88 Thanks for the fix, but unfortunately it's still not working. I'm still getting the same error message `Error: Can't find project for file: [redacted]/pom.xml`

**Comment by khalilou88** [comment]
@ToppScorer I created a workspace with your config and can't reproduce your error.

https://github.com/khalilou88/nx-workspace

**Comment by ToppScorer** [comment]
@khalilou88 I created a fork an updated the structure a little bit, to reproduce: https://github.com/khalilou88/nx-workspace/compare/main...ToppScorer:nx-workspace:main

In your example the `infrastructure` project also has a `project.json` which it should explicitly not have.

**Comment by khalilou88** [comment]
Can you try version 1.9.0, it should work for you. From version 1.10.0 it should break because of this change :https://github.com/khalilou88/jnxplus/pull/1297/files
Based on your reproduction, this project was not present in any modules tag.
I published version 1.16.1, where I change to error to warning and it should work for you now.

**Comment by ToppScorer** [comment]
@khalilou88 This is working now for me, thanks for the quick help, appreciate it. One question though:

`this project was not present in any modules tag` what exactly do you mean by that?

**Comment by khalilou88** [comment]
This: https://github.com/khalilou88/nx-workspace/commit/93464aef9f6c5ee0ea1b701db8159fee6049e629

```
  <modules>
    <module>../parent</module>
    <module>../../../apps/spring-boot/service/infrastructure</module>
  </modules>
```
