### ISSUE TITLE
Dependency graph issue with sub folders

### ISSUE THREAD

**Issue by lwhiteley** [khalilou88/jnxplus#15]
So first of all this plugin was very easy to use. Thanks..

Im seeing one issue which i think may not be supported but asking the question.

Im trying to do a setup where some java libs live in a sub folder but saw that the dependency graph doesnt pick up these projects as dependencies when listed

Steps:
```
- create a lib in a sub folder
 > nx generate @jnxplus/nx-boot-gradle:library messages/contacts-service  

- add dependency in gradle
- start `nx graph`
```

My sample gradle file excerpt
```gradle
// build.gradle for core-api

dependencies {
  	implementation 'org.springframework.boot:spring-boot-starter-web'
  	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	implementation project(":libs:offer-parser") // only this is shown as dependency (sometimes not)

        // these are unlinked always
	implementation project(":libs:messages:contacts-service")
	implementation project(":libs:messages:message-draft-service")
}
```

workspace,json
```jaon
{
  "version": 2,
  "projects": {
    "client": "apps/client",
    "client-e2e": "apps/client-e2e",
    "core-api": "apps/core-api",
    "messages/contacts-service": "libs/messages/contacts-service",
    "messages/message-draft-service": "libs/messages/message-draft-service",
    "offer-parser": "libs/offer-parser",
    "ui-buttons": "libs/ui/buttons",
    "ui-typography": "libs/ui/typography"
  }
}

```

Graph when nothing is shown as linked to `core-api`.
![graph (1)](https://user-images.githubusercontent.com/6108793/155300656-8c0f3815-a4a1-4a30-8e91-7cbecc5b2d0c.png)

and occasionally 
![graph (2)](https://user-images.githubusercontent.com/6108793/155301094-bbdcacd0-de09-4801-b7b9-fcbd6aa4b7af.png)

folder structure
![Screenshot 2022-02-23 at 11 30 35 AM](https://user-images.githubusercontent.com/6108793/155302149-9a00517f-f7f1-4e7a-b99b-fb6098704998.png)

Questions:
- Am i listing the dependencies incorrectly? (or incompatible with the lookup)
- Are sub folders currently supported by the dep-graph lookup for this library?
  - https://github.com/khalilou88/jnxplus/blob/main/packages/nx-boot-gradle/src/dep-graph/lookup-deps.ts#L86
  - only considers last part of the project name

**Comment by khalilou88** [comment]
Hi @lwhiteley Thank you for this detailed bug.
I just published a fix.
Hope it will fix your issue.

**Comment by lwhiteley** [comment]
Thanks I'll test again and let you know

**Comment by khalilou88** [comment]
Hi @lwhiteley Could you please tell me how you create a lib or an app inside a folder? which command you use?

**Comment by vladimirdrayling** [comment]
I'm trying to generate a lib inside a subfolder, but getting the following error:

```js
yarn run v1.22.17
$ /Users/vladimir.drayling/dev/web/apps/eon/node_modules/.bin/nx generate @jnxplus/nx-boot-maven:library --name=api --directory=greeting --groupId=de.eon --language=kotlin --projects=api --tags=scope:greeting,type:domain --no-interactive --dry-run
Cannot create Project 'api'. It already exists.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The terminal process "/bin/sh '-c', 'yarn nx generate @jnxplus/nx-boot-maven:library --name=api --directory=greeting --groupId=de.eon --language=kotlin --projects=api --tags=scope:greeting,type:domain --no-interactive --dry-run'" terminated with exit code: 1.
```

In fact I do have a project called `api` but it is inside of `apps` folder.

Is it possible to instruct the plugin to generate a lib called `greeting-api` with the folder structure like `libs/greeting/api`? It could make it possible to add `angular` libs e.g. `libs/greeting/feature` or `libs/greeting/ui`.

### angular|workspace.json

```json
{
  "version": 2,
  "projects": {
    "api": "apps/api",
    "greeting-api": "libs/greeting/api",
    "greeting-feature": "libs/greeting/feature",
    "greeting-ui": "libs/greeting/ui",
    "greeting-utils": "libs/greeting/utils",
    "web-client": "apps/web-client",
    "web-client-e2e": "apps/web-client-e2e"
  }
}
```

### nx report

```js
 >  NX   Report complete - copy this into the issue template

   Node : 16.13.1
   OS   : darwin x64
   yarn : 1.22.17
   
   nx : 13.8.4
   @nrwl/angular : 13.8.4
   @nrwl/cli : 13.8.4
   @nrwl/cypress : 13.8.4
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.4
   @nrwl/eslint-plugin-nx : 13.8.4
   @nrwl/express : undefined
   @nrwl/jest : 13.8.4
   @nrwl/js : undefined
   @nrwl/linter : 13.8.4
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.4
   @nrwl/tao : 13.8.4
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.4
   typescript : 4.5.5
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
         @angular/animations: 13.2.5
         @angular/common: 13.2.5
         @angular/compiler: 13.2.5
         @angular/core: 13.2.5
         @angular/forms: 13.2.5
         @angular/platform-browser: 13.2.5
         @angular/platform-browser-dynamic: 13.2.5
         @angular/router: 13.2.5
         @angular-devkit/build-angular: 13.2.5
         @angular/cli: 13.2.5
         @angular/compiler-cli: 13.2.5
         @angular/language-service: 13.2.5
         @jnxplus/nx-boot-maven: 1.4.1
```

**Comment by lwhiteley** [comment]
@khalilou88 

when creating the lib in a subfolder, you just define the path as the lib name

for eg.

```bash
nx generate @jnxplus/nx-boot-gradle:library {folder}/{project-name} 
```

i have not tried this with apps but it should work the same

**Comment by lwhiteley** [comment]
a thing to note is that the subfolder process for this lib is inconsistent with the core nx plugins..

where the core nx plugins hyphenate the project names. see workspace example below

```
{
  "version": 2,
  "projects": {
    "client": "apps/client",
    "client-e2e": "apps/client-e2e",
    "core-api": "apps/core-api",
    "messages/contacts-service": "libs/messages/contacts-service", // java plugin create names with `/`
    "messages/message-draft-service": "libs/messages/message-draft-service",
    "offer-parser": "libs/offer-parser",
    "ui-buttons": "libs/ui/buttons", // core nx plugins create project names with hyphens `-`
    "ui-typography": "libs/ui/typography"
  }
}
```


i had added a PR that searched for the real name so maybe take another look at the logic: https://github.com/khalilou88/jnxplus/pull/16

**Comment by lwhiteley** [comment]
@vladimirdrayling maybe unrelated but there is a migration bug with nx@13.8.4 so be careful until 13.8.5 is released

https://github.com/nrwl/nx/issues/9211

**Comment by vladimirdrayling** [comment]
The `nx generate @jnxplus/nx-boot-maven:library --name=greeting/api --groupId=de.eon --language=kotlin --projects=api --tags=scope:greeting,type:domain --no-interactive` generates the following content:

![image](https://user-images.githubusercontent.com/16114644/157039214-84d73ca7-7e4e-4945-9193-a258742f4c0c.png)

As you can see the file names are suffixed with `(1)`.

### angular.json

```json
{
  "version": 2,
  "projects": {
    "api": "apps/api",
    "greeting/api": "libs/greeting/api",
    "web-client": "apps/web-client",
    "web-client-e2e": "apps/web-client-e2e"
  }
}
```

As you @lwhiteley mentioned, the project's name could be hyphenate.

Is it possible to name the files with the directory's name? E.g. `nx generate @jnxplus/nx-boot-maven:library --name=api --directory=greeting --groupId=de.eon --language=kotlin --projects=api --tags=scope:greeting,type:domain --no-interactive --dry-run` would generate the following structure:

![image](https://user-images.githubusercontent.com/16114644/157041124-2775e904-5970-4d91-afce-4321009e2211.png)

with adjusted dependencies in `apps/api/(api.iml,pom.xml)` and `libs/greeting/api/(greeting-api.iml,pom.xml)`. Right now I just replaced the occurrence `greeting/api` with `greeting-api`.

### nx dep-graph

![image](https://user-images.githubusercontent.com/16114644/157042963-c4aad1c8-339d-4173-9527-28494a39e3b6.png)

**Comment by khalilou88** [comment]
we should not create a lib with a folder like this `nx generate @jnxplus/nx-boot-gradle:library {folder}/{project-name}`
the correct command is `nx generate @jnxplus/nx-boot-gradle:library {project-name} --directory {folder}`
I am fixing that, if the name contains a `/` I will change it to be `-`.

**Comment by khalilou88** [comment]
@lwhiteley @vladimirdrayling 
check this branch https://github.com/khalilou88/jnxplus/tree/feature/names
here I will make things simple and like nx generators

**Comment by lwhiteley** [comment]
took a quick look was not sure all cases are being handled.

Concerns to test for:

## Concern 1
the sub director can be multiple layers deep

```
libs/messages/shared/string-utils
```

```
nx generate @jnxplus/nx-boot-gradle:library  string-utils --directory messages/shared
```

## Concern 2

Need to test/handle case where developer wants to move project to a new folder

https://nx.dev/workspace/move#examples

This can also be multiple layers deep

## Concern 3 (nice to have)

Can the initial java package name be formatted nicely when directory given.

for eg created a lib with folder path `libs/messages/shared/string-utils`

package name can account for folders like

```java
package com.myapp.messages.shared.stringutils;
```

**Comment by khalilou88** [comment]
Hi @lwhiteley 
I will tackle point 1 and 3.
for point 4, it's hard to test it in dev env

point 2, lets put it on another task

**Comment by khalilou88** [comment]
@lwhiteley  I published the version 1.0.5 with this changes

**Comment by lwhiteley** [comment]
Tested with gradle

```
// Works
- [x] Concern 1
- [x] Concern 3

not working
- [ ] Concern 4 - not working
```

current workspace.json

```json
{
  "version": 2,
  "projects": {
    "client": "apps/client",
    "client-e2e": "apps/client-e2e",
    "core-api": "apps/core-api",
    "messages-shared-string-utils": "libs/messages/shared/string-utils",
    "messages/contacts-service": "libs/messages/contacts-service",
    "messages/message-draft-service": "libs/messages/message-draft-service",
    "offer-parser": "libs/offer-parser",
    "ui-buttons": "libs/ui/buttons",
    "ui-typography": "libs/ui/typography"
  }
}
```

<img width="997" alt="Screenshot 2022-03-08 at 5 24 48 PM" src="https://user-images.githubusercontent.com/6108793/157281122-2f8d5f69-a5a5-41fe-a681-8aa2ac65be2d.png">

**Comment by lwhiteley** [comment]
the project name lookup still isnt trying to find the real name but assuming it based on pattern

```
function getDependencyProjectName(gradleProjectPath: string) {
  return gradleProjectPath.split(':libs:').pop().replace(/:/g, '-');
}
```

wont work for all cases / be backward compatible
https://github.com/khalilou88/jnxplus/blob/main/packages/nx-boot-gradle/src/dep-graph/lookup-deps.ts#L86

**Comment by khalilou88** [comment]
@lwhiteley you are right about the graph. Could you please activate your PR for getting the exact project name ?

**Comment by lwhiteley** [comment]
sure no prob..

im also getting this error:

```
Error: Unable to access jarfile ./node_modules/@jnxplus/checkstyle/checkstyle.jar
```

**Comment by khalilou88** [comment]
@lwhiteley maybe you need to install deps? (npm install)

**Comment by lwhiteley** [comment]
I'm using pnpm . The dependency is there but not with Checkstyles folder

**Comment by khalilou88** [comment]
Maybe you can remove this   `"implicitDependencies": ["checkstyle", "pmd", "ktlint"]` from project.json?

**Comment by lwhiteley** [comment]
ah i get it now.. its just the install process seems different. it didnt install the other dependencies. ill have to check why

**Comment by lwhiteley** [comment]
ok i figured it out. the file structure for pnpm is different , 
it uses a virtual store for transitive dependencies so may need a way to define the location of the jar or resolve the location better.

relative path:
```
node_modules/.pnpm/@jnxplus+checkstyle@9.3.0/node_modules/@jnxplus/checkstyle/checkstyle.jar
```

**Comment by lwhiteley** [comment]
@khalilou88 
- dependency issues in PR #24 
- you can review and test #23 for graph project name look up

**Comment by lwhiteley** [comment]
@khalilou88 added one last PR.

let me know when tested and released

**Comment by khalilou88** [comment]
@lwhiteley thank you so much. I published your PRs in version 1.5.1

**Comment by lwhiteley** [comment]
nice .. i tested and all issues work great and is now backward compatible.

screenshot shows both types of project names are linked

<img width="1058" alt="Screenshot 2022-03-09 at 10 49 38 AM" src="https://user-images.githubusercontent.com/6108793/157416837-33032536-6421-4c39-86fe-c3c127af95bc.png">
